packages:
  - .
allowBuilds:
  cpu-features: true
  esbuild: true
  eslint-plugin-n8n-nodes-base: true
  isolated-vm: true
  ssh2: true
  unrs-resolver: true
onlyBuiltDependencies:
  - cpu-features
  - esbuild
  - eslint-plugin-n8n-nodes-base
  - isolated-vm
  - ssh2
  - unrs-resolver
